#lab_07 
Sean Mussenden

## About this lab

To complete this lab, you need to:
* write code in empty codeblocks provided to answer questions included (look for **Q**).
* write out the answer in the form of a complete sentence in the space given (look for **A**).

When you are finished, commit changes and push to your personal GitHub repo, then submit the URL to this document on ELMS.

## Load libraries and establish settings
**Task**: Make a code block and load janitor and the tidyverse

## Load data

For today's lab, we are using the DEA's ARCOS database, which tracks shipments of opioids and other controlled substances from manufacturers to pharmacies.  As we will read this week, the Washington Post used this data to show which communities were flooded by opioids during the death and overdose crisis of the last two decades. 

There are four tables in the data folder. 

* arcos.csv has the total number of opioid pills shipped to pharmacies located in each U.S. county each year (from 2006-2014). Each row represents one county in one year during that period. In some states, counties and cities are represented. Each county has a unique FIPS code, which stands for Federal Information Processing System (FIPS), which identify geographic areas. You will need this for both questions.
* county_population_2014.csv has the total population of each U.S. county (or city in some states) in 2014 from the American Community Survey. It has a unique numeric identifier for the county called GEOID. You will need to use this for the first question.
* state_population_2014.csv has the total population of each U.S. state in 2014 from the American Community Survey. You will need to use this for the second question.
* state_crosswalk.csv is a simple dataframe with two columns listing the state and its abbreviation.  You may need to use this for the second question.

**Task**: Create a codeblock and load the four dataframes using appropriate names below.

## Questions
**Task** Create codeblocks in the space below and answer the questions. 

**Q1** Which county or city received the most total opioid pills per person? Add up all the pills between 2006 and 2014 when doing this calculation. How many total pills, and what was the per person rate?

**Q2_New** 
Which U.S. state saw the highest percentage increase in opiod pills from 2006 to 2014? 

--Produce two tables, one for 2006 and one for 2014. In the 2006 table, rename the total to total_2006. In the 2014 table, rename the total to total_2014. 
--Join the tables into a new table, arcos_combo
--Your table must have the full name of the states. Join with the state crosswalk table
--Calculate the percentage change between 2006 and 2014
--Create one table with the top 5 states by percentage increase 
--Create a second table with the 5 states with the lowest percentage increase.

--Write a sentence that could be dropped in as the lede of a news story from the finding in question two. 


**Q3** Which U.S. state had the highest number of opioid pills per person for pills shipped in 2014? How many total pills, and what was the per person rate? How did that compare to Washington, D.C.?

