#lab_08
Sean Mussenden, Aug 16, 2022

## About this lab

To complete this lab, you need to:
* write code in empty codeblocks provided to answer questions included (look for **Q**).
* write out the answer in the form of a complete sentence in the space given (look for **A**).

When you are finished, commit changes and push to your personal GitHub repo, then submit the URL to this document on ELMS.

## Load libraries and establish settings
**Task**: Load janitor and the tidyverse

## Load data

**Task**: Load four tables of U.S. Census data.  Each table has one row per Maryland county with 2020 population information.  Each table has these same two columns:

* geoid - a unique identifier for each county
* name - the county name

The third column in each table represents the total population in one of four demographic categories.

* maryland_population.csv - total_pop - total population 
* maryland_hispanic.csv - hispanic_pop - total Hispanic population
* maryland_white.csv - white_pop - total White alone population
* maryland_black.csv - black_pop - total Black alone population

Some of the information in the tables may need to be cleaned or validated in order to produce the correct answer.  

## Questions

**Q1**  What Maryland county has the largest Hispanic population (by percentage of total population)? 
**A1** 

**Q2**  What is the total population of people who identify as white alone in Maryland? 
**A2**  

**Q3** What is the average Black population in all Maryland counties? 
**A3** 
