# Census Data {#census_data}

We will be using data from the U.S. Census for many of these exercises. Here's a quick rundown of the origins and inner-workings of this important dataset.

Each decade, the Census Bureau counts every person living in the United States and the five U.S. territories. This is known as the Decennial Census and it is used to apportion seats in the U.S. House of Representatives, among other things. 

In addition, the Census Bureau conducts ongoing survey of communities, known as the American Community Survey or ACS that provides more timely information about social, economic, housing, and demographic data every year. You can find information on housing, small business ownership, population profiles and much more. The ACS uses an annual sample size of about 3.5 million addresses and is collecting information daily. 

Congressional lawmakers look at the ACS data to determine distribution of federal spending, among other things. Read [more about census data here](https://www.census.gov/content/dam/Census/library/publications/2020/acs/acs_journalist_handbook_2020_ch1.pdf)

Here's something important to know about ACS results: Data are pooled across a calendar year. So the ACS numbers reflect data collected over a period of time. By contrast, the Decennial Census is a single point-in-time count of the population.

We will be using ACS data to examine trends in wealth and social issues in Baltimore neighborhoods because this survey provides detail not available yet in the Decennial Census.

You can access Census Data through multiple ways. The U.S. Census Bureau offers [data.census.gov](https://data.census.gov/cedsci/). Using this site requires some training and patience. Here is a good place to start, a [presentation the Census Bureau staff made](https://docs.google.com/presentation/d/1dUtT512SBa3FcVUPaBFwvLi2LaAwEFee/edit?usp=sharing&ouid=102324743793755798467&rtpof=true&sd=true) to the Investigative Reporters and Editors conference in 2019.

Another useful resource is [censusreporter.org](https://censusreporter.org/), a site not affiliated with the Census Bureau that's designed to make it easier to navigate and retrieve the ACS data. 

When we use R, we will use a software library called [tidycensus](https://walker-data.com/tidycensus/) that makes it very easy to retrieve Census data from the Census API, or application programming interface, basically a raw data feed optimized for R, python and similar programs. Stay tuned on that later this semester.

Data journalist Paul Overberg, now with The Wall Street Journal, compiled [this useful guide about terminology](assets/Census_Overberg_GuideToThePerplexed.pdf) when dealing with Census data.


