# Introduction

Welcome to data journalism. The main goal of this course is to expand your ability to report and tell stories using data. You will use these tools to discover trends in data. You will learn how to create and publish graphics and maps. It's hard work but it is a lot of fun and very rewarding.

We have some basic goals for you to reach in this class. By the end of the semester, we want you to have basic proficiency and independence with data analysis. We want you to be able to write about data clearly, using the Associated Press style as a benchmark. We want you to be able to find and download a dataset, clean it up, visualize it.

The skills you will learn in the coming weeks are in high demand in journalism and beyond. Examine this BuzzFeed job description from 2017:

"We're looking for someone with a passion for news and a commitment to using data to find amazing, important stories --- both quick hits and deeper analyses that drive conversations," the posting seeking a data journalist says. It goes on to list five things BuzzFeed is looking for: Excellent collaborator, clear writer, deep statistical understanding, knowledge of obtaining and restructuring data.

**"You should have a strong command of at least one toolset that (a) allows for filtering, joining, pivoting, and aggregating tabular data, and (b) enables reproducible workflows."**

You will learn these skills in this book. You'll get a taste of modern data journalism through Google Sheets and programming in R, a statistics language. You'll be challenged to think programmatically while thinking about a story you can tell to readers in a way that they'll want to read. Combining them together has the power to change policy, expose injustice and deeply inform.

## Installations

This book begins with a basic review of Google Sheets and then shifts to the R statistical language. To follow along, you'll do the following:

1.  Install the R language on your computer. Go to the [this website](http://lib.stat.cmu.edu/R/CRAN/), click download R based on your operating system. If that link somehow doesn't work, check [R Project website](https://www.r-project.org/) and find a different location.

2.  Install [R Studio Desktop](https://www.rstudio.com/products/rstudio/#Desktop). The free version is great.

Going forward, you'll see passages like this:

```{r eval=FALSE}
install.packages("tidyverse")
```

That is code that you'll need to run common software packages in your R Studio. 

## About this book

This book is the collection of class materials compiled by various data journalism professors around the country: Matt Waite at the University of Nebraska-Lincoln's College of Journalism and Mass Communications and Sarah Cohen of Arizona State University. This version was edited by Derek Willis, Sean Mussenden and Rob Wells at the University of Maryland Philip Merrill College of Journalism.

There's some things you should know about it:

-   It is free for students.
-   The topics will remain the same but the text is going to be constantly tinkered with.
-   What is the work of the authors is copyright Rob Wells 2024, Sean Mussenden and Derek Willis 2022, Matt Waite 2020 and Sarah Cohen 2022.
-   The text is [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) Creative Commons licensed. That means you can share it and change it, but only if you share your changes with the same license and it cannot be used for commercial purposes. I'm not making money on this so you can't either.
-   As such, the whole book -- authored in Quarto -- in its original form is [open sourced on Github](https://wellsdata.github.io/data_journalism_class/). Pull requests welcomed!

## What we'll cover

-   Spreadsheets
-   R Basics
-   Replication, Data Diary
-   Data basics and structures
-   Aggregates
-   Mutating
-   Working with dates
-   Filters
-   Data cleaning techniques, Janitor
-   Pulling Data from PDFs
-   Joins
-   Basic data scraping
-   Getting data from APIs: Census
-   Visualizing for reporting: Basics
-   Visualizing for reporting: Publishing
-   Geographic data basics
-   Geographic queries
-   Geographic visualization
-   Text analysis basics
-   Writing with and about data
-   Data journalism ethics
