When you produce findings from analysis that you want to share with non-technical colleagues -- your code-allergic editor, perhaps -- you can't always expect them to be able to load up RStudio to run your code themselves. And you definitely can't expect readers to do that, if you want to share the findings that support a story you've published.

Fortunately, working in Quarto markdown documents -- .QMD files -- allows us to easily publish a nice and tidy html page (or, if we prefer, a pdf or a word doc) with the results of our analysis. We can publish a page that contains text, tables, static or interactive visualizations, images, links and, if we want to show it, our code.

The process works like this:

1.  Create a QMD with your analysis, and some special code that helps determine what the html document that's created will look like. This includes:
  * Overall settings for our document using YAML, more on this below.
  * Styled text using Markdown codes in text blocks. 
  * Special code in codeblocks that determines how they render.
2.  Click the "Render" button (with a big blue arrow) above. 
3.  Open the resulting html file in a web browser. 

Let's get an overview of the different parts of the QMD file, and then we'll practice in another document.

##  The top matter

At the top of the page is something we've seen in our templates for our major projects. It's called "YAML", and it provides styling and other information that will be included in the final html document we create. 

In the example below, we're providing a very bare bones set of YAML instructions.  We're giving our document a title, an author, a date (each time it's run, the current date will be put in) and telling the document to output as html and use a built-in styling "theme" called cosmo. 

```
---
title: "A guide to Quarto Markdown"
author: "Sean Mussenden"
date: "`r Sys.Date()`"
format:
  html:
    theme: cosmo
---

```
We can also easily add a clickable table of contents and more, as this [nice guide shows](https://quarto.org/docs/output-formats/html-basics.html#table-of-contents)


## Styled Text

At the core, QMD files are text files, and they allow you to use a very lightweight "markup" language to style text, similar to html, but much less fussy than html. 

Outside of the codeblocks (the gray sections where we write code), we can style any text using standard markdown styling. 

This is a nice guide to styling text with markdown: [Markdown guide ](https://quarto.org/docs/authoring/markdown-basics.html)

We can create headings similar to html's <h1> to <h6> with hashtags.  

##### This is an h5

We can create links, like this: [google](https://google.com)

We can **bold** or *italic* text. 

We can create bulleted lists

* bullet one
* bullet two
* bullet three

## Code blocks

We can also add special code inside of code blocks -- the gray sections where we write code -- that control how they render in our html document.  These output options let us do things like:

* Show or hide the code when we render our html document  (echo: true or false)
* Prevent the code from actually running when we render our html document (eval: true or false)
* Hide warnings from outputing when we render our html document (warning: true or false)

There's a [full guide here](https://quarto.org/docs/computations/execution-options.html#output-options).

The code below, for example, will output the text inside the print statement when rendered to html, but the actual code -- the print() function -- will be hidden.

```{r}
#| echo: false
print("the code will be hidden in the rendered html document, but this will output")
```
