# Spreadsheets 

# Introduction {#xl-intro .unnumbered}

Spreadsheets are the gateway drug of data journalism. 

They are fundamental for organizing data and doing quick calculations. The concepts of sorting, filtering and calculations with spreadsheets are adapted to advanced software. Every data journalist has a solid proficiency in spreadsheets. After readings this material and doing the exercises, you will be on your way too.

Spreadsheets are great because it's relatively easy to see what you're doing and you can easily share your work with your colleagues. In fact, pieces of the [Pulitzer-Prize winning COVID-19 coverage](https://www.pulitzer.org/winners/new-york-times-6) from The New York Times was compiled using an elaborate and highly tuned set of Google spreadsheets with dozens of contributors.

This guide uses Google Sheets, which allows students to do the exercises regardless of their computer operating system, Mac, Windows or Linux. The exercises can be easily adapted to Microsoft Excel, which can handle larger datasets and has more options for pivot tables and other more advanced functions. However, Google Sheets have their own advanced functions for scraping websites or importing non-tabular file formats like JSON.

[Most of the screen shots and instructions are created with a MacOS Monterey. Some come from earlier Mac versions, but are largely the same now. **Windows users should replace any instructions for using the CMD- key with the CTL- key.** There is a table that compares keystrokes for Apple desktops, laptops and Windows machines for Excel at the bottom of]{.underline} [Spreadsheet Refresher](xl-refresher)

## Tutorials {.unnumbered}

Spreadsheets are used in almost every workplace in America. This section covers most of what you need in the newsroom.

-   [Spreadsheet Refresher](xl-refresher.html) : Start over with good habits

-   [Sorting and filtering to find stories](xl-filter-sort.html) : The first step of interviewing data

-   [Grouping with pivot tables](xl-pivot.html): Aggregating, and the super power of spreadsheets

-   [Spreadsheet Formulas](xl-formulas.html): Percents, sums, and other basic computations used in newsrooms.


