#lab_12
Sean Mussenden, Aug 16, 2022

## About this lab

To complete this lab, you need to:
* write code in empty codeblocks provided to answer questions included (look for **Q**).
* write out the answer in the form of a complete sentence in the space given (look for **A**).

When you are finished, commit changes and push to your personal GitHub repo, then submit the URL to this document on ELMS.

## Overview

There is one main goal of this lab:

* To apply your knowledge of basic web scraping.
* To integrate scraped data with other data pulled from API packages.

You will do this by scraping data from the Maryland State Board of Election website, and connecting it with U.S. Census data pulled from the Tidycensus package to answer questions that can be answered with one or more data sets. 

You can find election results here: https://elections.maryland.gov/elections/2022/general_results/

## Load libraries and settings

**Task**: load the tidyverse, tidycensus, rvest and janitor.  Store your Census api key.

## Questions

**Q1** Which candidate, Dan Cox or Wes Moore, got the lowest percentage of their votes on Election Day? What does that suggest? Write up your answer in a sentence. 
**A1**

**Q2** How many counties did Chris Van Hollen win in Maryland's Senate race? 
**A2** 

**Q3** What percentage of the vote did Chris Van Hollen in Maryland's wealthiest county by median income. (You must use the Tidycensus package to answer this question).
**A3** 
