#lab_08
Sean Mussenden, Aug 16, 2022

## About this lab

To complete this lab, you need to:
* write code in empty codeblocks provided to answer questions included (look for **Q**).
* write out the answer in the form of a complete sentence in the space given (look for **A**).

When you are finished, commit changes and push to your personal GitHub repo, then submit the URL to this document on ELMS.

## Load libraries and establish settings
**Task**: Load janitor and the tidyverse and sf

## Load data

You have been given two spatial dataframes and one regular dataframe to load.  The dataframes are:

* baltimore_homicides.rds | spatial | location and details about each Baltimore homicide between 2007 and 2017, including information about the status (open, closed with arrest, closed without arrest) and the exact location. Details on the data: https://github.com/washingtonpost/data-homicides
* baltimore_tract_shapefiles.rds | spatial | polygons of each census tract in Baltimore
* baltimore_tract_demographics.rds | regular | the total population and white population of each baltimore Census tract in 2017.

**Task** Load the data

## Questions

**Q1** Are homicides that occur in majority white Census tracts in Baltimore solved at a higher rate than homicides in non-majority white Baltimore census tracts?
* Write up your findings in three paragraphs that could be dropped into a news story, with the answer to the question as the lede. 
* Include any other relevant details.
* Output a table with relevant results. 
* Output at least one map visualization pertinent to your finding. 

**A1** 


