#lab_10
Sean Mussenden, Aug 16, 2022

## About this lab

To complete this lab, you need to:
* write code in empty codeblocks provided to answer questions included (look for **Q**).
* write out the answer in the form of a complete sentence in the space given (look for **A**).

When you are finished, commit changes and push to your personal GitHub repo, then submit the URL to this document on ELMS.

## Load libraries and establish settings
**Task**: Load janitor, the tidyverse, sf and leaflet.

## Motivation for analysis

You are reporting a story looking at how the pervasiveness of gun violence affects student learning, and decide you want to identify a school in Washington, D.C. that has had multiple gunshot events on or very near school grounds during the schoolday when school was open.

You have a dataframe of timestamped and geolocated gunshots between 2014 and 2022, captured from a network of Shot Spotter microphones located throughout the city that use sound to triangulate shot locations. 

You also have a dataframe of when schools were open in 2019 and another with the geolocation of each school. 

In answering the following questions, you'll want to only examine shooting events that:

* Occurred on school days when school was open in calendar year 2019.
* Occurred during school hours (defined as 7 a.m. to 4 p.m.).
* Occurred within 200 meters of a school.
* Are not gunshots that might have been mislabeled as fireworks by the Shot Spotter network. 

## Load data

You have been given four dataframes to load.  One is a regular dataframe. The other three are spatial dataframes.  

The dataframes are:

* shot_spotter.rds | spatial points | location of gunshots in DC between 2014 and 2022.  
  * Triangulated latitude and longitude position of gunshots based on sound collected from microphones across the city. https://www.shotspotter.com/law-enforcement/gunshot-detection-technology/
  * Details on the data: https://opendata.dc.gov/datasets/89bfd2aed9a142249225a638448a5276_29/about
* washington_schools.rds | spatial points | location of each school in Washington.
* dc_school_days_2019.rds | regular dataframe | indicates whether DC schools were open and closed on a given date.
* washington_shapefile.rds | spatial polygon | outline of Washington DC, if you need it for mapping. You don't have to use this, only if you find it helpful to visualize things.

## Questions

**Q1** Students in what Washington school were exposed to the most gunshot events during school hours in 2019? How many?
**A1** 

**Q2** How many distinct shooting events were there within 200 meters of any DC school in 2019, during school hours?
**A2** 

**Q3** How many distinct schools had a shooting event within 200 meters in 2019, during school hours?
**A3** 

**Q4** Produce a dataframe with the shootings that occurred near the answer to question 1. Write an anecdotal top of a story centering on shootings near that school in 2019, followed by a few paragraphs of context from the answers to question 2 and 3.  
**A4**


