#Lab_02 {lab_02}

### About this lab

To complete this lab, you need to: 
Perform the assigned tasks as directed (look for **Task**).
-  #1 Create a Google Sheet, load the assigned data, and answer the questions.
-  #2 Create a new tab for each Exercise. 
-  #3 When you are finished, open the share settings on Sheets, allow the instructor access, copy the URL and paste it into the submisssion box.

**Task** 

### Exercise #1: Filtering and sorting

This exercise helps you understand the difference between filtering and grouping, or, in spreadsheet terms, filtering and pivot tables. In general, you'll use filtering to look up the details of cases based on a criteria. You'll use pivot tables to create aggregated data -- count, sum, average, and the like.

In the real world, reporters move back and forth between these two techniques. They'll go back and filter for cases once they find something interesting in the aggregation, and will create sums and counts if they think they see a pattern in the cases.

### Data source

- Download data for [Maryland race by city, place for 2010 - 2020](assets/data/md_race_all_8_13.csv)

-   Open Google Sheets. File \| Import \| Upload \| Select the downloaded file "md_race_all_8_13.csv" . After it uploads, select the green "Import Data" button.

In this data set, each row represents a city or town in Maryland with the 2010 and 2020 figures for: 

-  Total population 
-  White only population
-  Black or African American only population
-  Hispanic only population 
-  Native American only population
-  Asian only population
-  Pacific Islander (including native Hawaiian) only population

Background on this data from [Social Explorer](https://www.socialexplorer.com/data/ACS2016_5yr/metadata/?ds=ACS16_5yr&table=B02001) 

## Sort / filter

- 1.  Filter the sheet for Baltimore city, provide the 2020 population for white, Black, Hispanic, Native American, Asian, Pacific Islander.

- 2.  For all places, create a new column and calculate the percentage change for total population from 2010-2020. Which place had the highest growth? Which had the least? Rank the list. Where was Baltimore on that list, its percentage growth and its ranking?

- 3.  For all places, create a new column and calculate the percentage change in the white population from 2010-2020. Do the same for the Black and Hispanic
population. 
Which places had the greatest and least growth in the white population? 
Which places had the greatest and least growth in the Black population? 
Which places had the greatest and least growth in the Hispanic population? 
Describe the growth trends for these three groups for Baltimore.

- 4. For all places, create a new column to determine the percentage of white people to the total population in 2020. How many all white towns are there in Maryland?

- 5. Determine the average total population for 2020. Then filter out all of the places below that average and copy the results of the cities with the above average population to a new sheet, and call it bigger_cities. How many cities / towns are on that list?

**Task** 

### Exercise #2: Pivot table

For this question, load data for [Maryland race data for pivot table 2010 - 2020](assets/data/md_race_pivot_8_13.csv)

-   Open Google Sheets. File \| Import \| Upload \| Select the downloaded file "md_race_all_8_13.csv" . After it uploads, select the green "Import Data" button.

This is the same data but structured in a format to simplify the pivot table questions.

Construct a pivot table with md_race_pivot_8_13. Answer the following questions:

-  6. Provide a summary of population by all races, filtered to 2020. (Pro tip: do not click Show Totals.) How does the overall population compare to the total Maryland population in 2020? 

- 7. Provide the average population for all races, filtered to 2020. Which racial group is the smallest by average?

**Task** 

### Exercise #3. Cleaning

We will use a version of the Washington Post [police shooting data](https://docs.google.com/spreadsheets/d/13RohaTGgnUhxw5KMKT_BhZe45QQDz62gYbagwoztpLk/edit?usp=sharing) to conduct these exercises.

Using the skills learned in the Sheets Cleaning chapter, normalize the Black and African Am values in race_ethnicity2 and then calculate the total of all shootings by race / ethnicity in a pivot table. 

- 8. What is the total number of Black people who had been shot?


